// <auto-generated />
using System;
using HeartForCharity.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeartForCharity.Services.Migrations
{
    [DbContext(typeof(HeartForCharityDbContext))]
    partial class HeartForCharityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeartForCharity.Services.Database.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StreetName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AddressId");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Campaign", b =>
                {
                    b.Property<int>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampaignId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganisationProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CampaignId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OrganisationProfileId");

                    b.HasIndex("Status");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.CampaignMedia", b =>
                {
                    b.Property<int>("CampaignMediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampaignMediaId"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CampaignMediaId");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignMedias");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("AppliesTo")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("ISOCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DonationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<string>("PayPalOrderId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PayPalTransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("DonationId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("SentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("VolunteerApplicationId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("VolunteerApplicationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.OrganisationProfile", b =>
                {
                    b.Property<int>("OrganisationProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganisationProfileId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OrganisationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrganisationProfileId");

                    b.HasIndex("AddressId");

                    b.HasIndex("OrganisationTypeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("OrganisationProfiles");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.OrganisationType", b =>
                {
                    b.Property<int>("OrganisationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganisationTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrganisationTypeId");

                    b.ToTable("OrganisationTypes");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Recommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationId"));

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("RecommendationId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganisationProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("VolunteerApplicationId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("OrganisationProfileId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("VolunteerApplicationId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserProfileId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.VolunteerApplication", b =>
                {
                    b.Property<int>("VolunteerApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteerApplicationId"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoverLetter")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResumeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("VolunteerJobId")
                        .HasColumnType("int");

                    b.HasKey("VolunteerApplicationId");

                    b.HasIndex("Status");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("VolunteerJobId", "UserProfileId")
                        .IsUnique();

                    b.ToTable("VolunteerApplications");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.VolunteerJob", b =>
                {
                    b.Property<int>("VolunteerJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteerJobId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("bit");

                    b.Property<int>("OrganisationProfileId")
                        .HasColumnType("int");

                    b.Property<int>("PositionsAvailable")
                        .HasColumnType("int");

                    b.Property<int>("PositionsFilled")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("VolunteerJobId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OrganisationProfileId");

                    b.HasIndex("Status");

                    b.ToTable("VolunteerJobs");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.VolunteerSkill", b =>
                {
                    b.Property<int>("VolunteerSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteerSkillId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("VolunteerSkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserProfileId", "SkillId")
                        .IsUnique();

                    b.ToTable("VolunteerSkills");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Address", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Campaign", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.Category", "Category")
                        .WithMany("Campaigns")
                        .HasForeignKey("CategoryId");

                    b.HasOne("HeartForCharity.Services.Database.OrganisationProfile", "OrganisationProfile")
                        .WithMany("Campaigns")
                        .HasForeignKey("OrganisationProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("OrganisationProfile");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.CampaignMedia", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.Campaign", "Campaign")
                        .WithMany("CampaignMedias")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.City", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Donation", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.Campaign", "Campaign")
                        .WithMany("Donations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeartForCharity.Services.Database.UserProfile", "UserProfile")
                        .WithMany("Donations")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Campaign");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Notification", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.UserProfile", "UserProfile")
                        .WithMany("Notifications")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeartForCharity.Services.Database.VolunteerApplication", "VolunteerApplication")
                        .WithMany("Notifications")
                        .HasForeignKey("VolunteerApplicationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UserProfile");

                    b.Navigation("VolunteerApplication");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.OrganisationProfile", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.Address", "Address")
                        .WithMany("OrganisationProfiles")
                        .HasForeignKey("AddressId");

                    b.HasOne("HeartForCharity.Services.Database.OrganisationType", "OrganisationType")
                        .WithMany("OrganisationProfiles")
                        .HasForeignKey("OrganisationTypeId");

                    b.HasOne("HeartForCharity.Services.Database.User", "User")
                        .WithOne("OrganisationProfile")
                        .HasForeignKey("HeartForCharity.Services.Database.OrganisationProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("OrganisationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Recommendation", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.UserProfile", "UserProfile")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.RefreshToken", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Review", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.OrganisationProfile", "OrganisationProfile")
                        .WithMany("Reviews")
                        .HasForeignKey("OrganisationProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeartForCharity.Services.Database.UserProfile", "UserProfile")
                        .WithMany("Reviews")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeartForCharity.Services.Database.VolunteerApplication", "VolunteerApplication")
                        .WithOne("Review")
                        .HasForeignKey("HeartForCharity.Services.Database.Review", "VolunteerApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganisationProfile");

                    b.Navigation("UserProfile");

                    b.Navigation("VolunteerApplication");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.UserProfile", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.Address", "Address")
                        .WithMany("UserProfiles")
                        .HasForeignKey("AddressId");

                    b.HasOne("HeartForCharity.Services.Database.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("HeartForCharity.Services.Database.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.VolunteerApplication", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.UserProfile", "UserProfile")
                        .WithMany("VolunteerApplications")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeartForCharity.Services.Database.VolunteerJob", "VolunteerJob")
                        .WithMany("VolunteerApplications")
                        .HasForeignKey("VolunteerJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserProfile");

                    b.Navigation("VolunteerJob");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.VolunteerJob", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.Address", "Address")
                        .WithMany("VolunteerJobs")
                        .HasForeignKey("AddressId");

                    b.HasOne("HeartForCharity.Services.Database.Category", "Category")
                        .WithMany("VolunteerJobs")
                        .HasForeignKey("CategoryId");

                    b.HasOne("HeartForCharity.Services.Database.OrganisationProfile", "OrganisationProfile")
                        .WithMany("VolunteerJobs")
                        .HasForeignKey("OrganisationProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Category");

                    b.Navigation("OrganisationProfile");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.VolunteerSkill", b =>
                {
                    b.HasOne("HeartForCharity.Services.Database.Skill", "Skill")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeartForCharity.Services.Database.UserProfile", "UserProfile")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Address", b =>
                {
                    b.Navigation("OrganisationProfiles");

                    b.Navigation("UserProfiles");

                    b.Navigation("VolunteerJobs");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Campaign", b =>
                {
                    b.Navigation("CampaignMedias");

                    b.Navigation("Donations");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Category", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("VolunteerJobs");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.OrganisationProfile", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Reviews");

                    b.Navigation("VolunteerJobs");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.OrganisationType", b =>
                {
                    b.Navigation("OrganisationProfiles");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.Skill", b =>
                {
                    b.Navigation("VolunteerSkills");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.User", b =>
                {
                    b.Navigation("OrganisationProfile");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.UserProfile", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Notifications");

                    b.Navigation("Recommendations");

                    b.Navigation("Reviews");

                    b.Navigation("VolunteerApplications");

                    b.Navigation("VolunteerSkills");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.VolunteerApplication", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("HeartForCharity.Services.Database.VolunteerJob", b =>
                {
                    b.Navigation("VolunteerApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
